autoconf: fix in6_pktinfo auto detection
This commig fixes auto detection of in6_pktinfo.
When negotiationg an IPv6 IKE session charon report an error
"Jun 30 16:42:49 03[NET] error reading IP header"

The cause of error is missing in6_pktinfo, which is auto detected.
The auto detection appears to fail with

configure:19850: checking for in6_pktinfo
configure:19870: gcc -c -g -O0 -Wall -Wno-format -Wno-format-security
-Wno-pointer-sign -Werror -Wfatal-errors -Wno-error=stringop-truncation
conftest.c >&5
conftest.c: In function 'main':
conftest.c:73:11: error: 'pi.ipi6_ifindex' is used uninitialized in this
function [-Werror=uninitialized]
   73 |     if (pi.ipi6_ifindex)
      |         ~~^~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors

Signed-off-by: Antony Antony <antony.antony@secunet.com>